'use client';

import { useEffect, useState } from 'react';
import { Sparkles, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { MessageResponse } from '@/components/MessageResponse';
import { Badge } from '@/components/ui/badge';

export function BriefingCard() {
 const [markdown, setMarkdown] = useState<string | null>(null);
 const [loading, setLoading] = useState(false);
 const [mock, setMock] = useState(true);

 async function load() {
  setLoading(true);
  try {
   const res = await fetch('/api/briefing', { method: 'POST' });
   const data = (await res.json()) as { markdown: string; mock: boolean };
   setMarkdown(data.markdown);
   setMock(data.mock);
  } finally {
   setLoading(false);
  }
 }

 useEffect(() => {
  void load();
 }, []);

 return (
  <div className="rounded-xl bg-evari-surface p-6 relative overflow-hidden">
   <div className="absolute inset-0 evari-grid opacity-[0.04] pointer-events-none" />
   <div className="relative">
    <div className="flex items-start justify-between gap-4 mb-4">
     <div className="flex items-center gap-2.5">
      <div className="h-8 w-8 rounded-lg bg-evari-gold flex items-center justify-center">
       <Sparkles className="h-4 w-4 text-evari-goldInk" />
      </div>
      <div>
       <div className="text-sm font-medium text-evari-text leading-tight">Morning briefing</div>
       <div className="text-xs text-evari-dim mt-0.5">
        Generated by Claude in your voice
       </div>
      </div>
     </div>
     <div className="flex items-center gap-2">
      {mock && (
       <Badge variant="warning" className="text-[10px]">
        fallback
       </Badge>
      )}
      <Button
       variant="ghost"
       size="sm"
       onClick={() => void load()}
       disabled={loading}
       className="text-xs"
      >
       <RefreshCw className={`h-3 w-3 ${loading ? 'animate-spin' : ''}`} />
       Regenerate
      </Button>
     </div>
    </div>

    <div className="min-h-[160px]">
     {loading && !markdown ? (
      <div className="space-y-2">
       <div className="h-3 w-3/4 bg-evari-edge rounded animate-pulse" />
       <div className="h-3 w-2/3 bg-evari-edge rounded animate-pulse" />
       <div className="h-3 w-5/6 bg-evari-edge rounded animate-pulse" />
       <div className="h-3 w-1/2 bg-evari-edge rounded animate-pulse" />
      </div>
     ) : markdown ? (
      <MessageResponse>{markdown}</MessageResponse>
     ) : null}
    </div>
   </div>
  </div>
 );
}
