'use client';

import { useEffect, useRef, useState } from 'react';
import { Check } from 'lucide-react';
import { applyAccent, useTheme, type Ink } from './ThemeProvider';

/**
 * Full-spectrum colour picker for the app's accent colour. Drives every
 * highlight — CTA buttons, the to-do count pill, pinned icons, active links.
 *
 * Ink (text on accent) uses a draft + explicit SAVE flow so choices feel
 * committed rather than autosaved in the background. Clicking a preview
 * updates the live CSS so the user sees the effect everywhere instantly,
 * but the preference only persists to localStorage when they hit Save.
 * If they navigate away without saving, the committed value is re-applied
 * on the next page load.
 */
export function AccentPicker() {
  const { accent, setAccent, ink, setInk } = useTheme();

  // Draft mirrors committed ink on mount and on committed-ink changes
  // (e.g. theme toggle re-hydrates). Clicking a preview updates the draft
  // and pushes it through `applyAccent` for a live CSS preview, without
  // touching the stored preference until Save.
  const [draftInk, setDraftInk] = useState<Ink>(ink);
  const [justSaved, setJustSaved] = useState(false);
  const savedTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    setDraftInk(ink);
  }, [ink]);

  useEffect(() => {
    return () => {
      if (savedTimer.current) clearTimeout(savedTimer.current);
    };
  }, []);

  function previewInk(next: Ink) {
    setDraftInk(next);
    // Live CSS preview — no persistence yet.
    applyAccent(accent, next);
  }

  function handleSave() {
    setInk(draftInk);
    setJustSaved(true);
    if (savedTimer.current) clearTimeout(savedTimer.current);
    savedTimer.current = setTimeout(() => setJustSaved(false), 1800);
  }

  const dirty = draftInk !== ink;
  const resolvedInk = resolveInk(accent, draftInk);

  return (
    <div className="flex flex-col gap-4 w-full max-w-xs">
      {/* Accent colour ---------------------------------------------------- */}
      <div className="flex flex-col gap-3">
        <div className="flex items-center justify-between text-[11px]">
          <span className="uppercase tracking-[0.14em] text-evari-dimmer font-medium">
            Accent colour
          </span>
          <span className="text-evari-dim font-mono tabular-nums">
            {accent.toUpperCase()}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <label
            className="relative h-9 w-9 rounded-md overflow-hidden cursor-pointer shrink-0"
            style={{
              background: accent,
              boxShadow: '0 0 0 1px rgb(var(--evari-edge))',
            }}
            title="Pick any colour"
          >
            <input
              type="color"
              value={accent}
              onChange={(e) => setAccent(e.target.value)}
              className="absolute inset-0 opacity-0 cursor-pointer"
            />
          </label>
          <div className="text-[11px] text-evari-dim leading-snug">
            Click the swatch to open the colour wheel.
          </div>
        </div>
      </div>

      {/* Ink (text on accent) -------------------------------------------- */}
      {/* Vertical rhythm is one button-height (36px) between every sub-row:
          label → buttons → lozenges → save. Using inline style (rather than
          Tailwind's gap-9) so it cannot silently regress if the utility
          isn't generated by the JIT. */}
      <div className="flex flex-col" style={{ gap: '36px' }}>
        <div className="flex items-center justify-between text-[11px]">
          <span className="uppercase tracking-[0.14em] text-evari-dimmer font-medium">
            Text on accent
          </span>
          <span className="text-evari-dim font-mono">
            {draftInk === 'auto'
              ? `AUTO · ${resolvedInk === 'light' ? 'LIGHT' : 'DARK'}`
              : draftInk.toUpperCase()}
          </span>
        </div>

        {/* Row 1 — full-size button previews */}
        <div className="grid grid-cols-2 gap-2">
          <ButtonSwatch
            accent={accent}
            inkRgb={inkRgb('light')}
            active={draftInk === 'light'}
            onClick={() => previewInk('light')}
            label="Light text"
          />
          <ButtonSwatch
            accent={accent}
            inkRgb={inkRgb('dark')}
            active={draftInk === 'dark'}
            onClick={() => previewInk('dark')}
            label="Dark text"
          />
        </div>

        {/* Row 2 — smaller lozenges, left-aligned so there's open space to
            the right of each (matches how REVIEW pills render elsewhere) */}
        <div className="grid grid-cols-2 gap-2">
          <div className="flex items-center">
            <LozengeSwatch
              accent={accent}
              inkRgb={inkRgb('light')}
              active={draftInk === 'light'}
              onClick={() => previewInk('light')}
              label="REVIEW"
            />
          </div>
          <div className="flex items-center">
            <LozengeSwatch
              accent={accent}
              inkRgb={inkRgb('dark')}
              active={draftInk === 'dark'}
              onClick={() => previewInk('dark')}
              label="REVIEW"
            />
          </div>
        </div>

        {/* Auto reset + Save */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => previewInk('auto')}
            className={
              'flex-1 text-[10px] uppercase tracking-[0.14em] font-medium py-2 rounded-md transition-colors ' +
              (draftInk === 'auto'
                ? 'bg-evari-surfaceSoft text-evari-text'
                : 'text-evari-dim hover:text-evari-text hover:bg-evari-surfaceSoft/50')
            }
          >
            Auto ({resolvedInk})
          </button>
          <button
            type="button"
            onClick={handleSave}
            disabled={!dirty && !justSaved}
            className={
              'flex-1 text-[11px] uppercase tracking-[0.14em] font-semibold py-2 rounded-md transition-all inline-flex items-center justify-center gap-1.5 ' +
              (justSaved
                ? 'bg-evari-success text-evari-ink'
                : dirty
                ? 'bg-evari-gold text-evari-goldInk hover:brightness-110'
                : 'bg-evari-surfaceSoft text-evari-dimmer cursor-not-allowed')
            }
          >
            {justSaved ? (
              <>
                <Check className="h-3.5 w-3.5" />
                Saved
              </>
            ) : (
              'Save'
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Preview swatches
// ---------------------------------------------------------------------------

function ButtonSwatch({
  accent,
  inkRgb,
  active,
  onClick,
  label,
}: {
  accent: string;
  inkRgb: string;
  active: boolean;
  onClick: () => void;
  label: string;
}) {
  // Outline only when selected — the rest of the site never wears a resting
  // border on non-active controls, so these previews shouldn't either.
  const ring = active
    ? 'outline outline-2 outline-offset-2 outline-evari-text'
    : '';
  return (
    <button
      type="button"
      onClick={onClick}
      className={`relative flex items-center justify-center transition-all cursor-pointer h-9 rounded-md text-xs font-medium ${ring}`}
      style={{ background: accent, color: `rgb(${inkRgb})` }}
    >
      {label}
    </button>
  );
}

function LozengeSwatch({
  accent,
  inkRgb,
  active,
  onClick,
  label,
}: {
  accent: string;
  inkRgb: string;
  active: boolean;
  onClick: () => void;
  label: string;
}) {
  // Outline only when selected (see ButtonSwatch).
  const ring = active
    ? 'outline outline-2 outline-offset-2 outline-evari-text'
    : '';
  return (
    <button
      type="button"
      onClick={onClick}
      className={
        'inline-flex items-center justify-center rounded-full px-2.5 py-0.5 text-[10px] font-semibold tracking-[0.08em] transition-all cursor-pointer ' +
        ring
      }
      style={{ background: accent, color: `rgb(${inkRgb})` }}
    >
      {label}
    </button>
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function inkRgb(which: 'light' | 'dark'): string {
  return which === 'light' ? '245 245 245' : '20 20 20';
}

function resolveInk(accent: string, pref: Ink): 'light' | 'dark' {
  if (pref === 'light') return 'light';
  if (pref === 'dark') return 'dark';
  // auto — mirror ThemeProvider's luminance rule
  const h = accent.replace('#', '');
  if (h.length < 6) return 'dark';
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  if (isNaN(r) || isNaN(g) || isNaN(b)) return 'dark';
  const luma = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return luma < 150 ? 'light' : 'dark';
}
