import Link from 'next/link';
import { TopBar } from '@/components/sidebar/TopBar';
import { createSupabaseAdmin } from '@/lib/supabase/admin';
import { listPlays } from '@/lib/dashboard/repository';
import type { Play, PlayStage } from '@/lib/types';
import { cn } from '@/lib/utils';
import { Pin, Plus } from 'lucide-react';
import { relativeTime } from '@/lib/utils';

const STAGES: {
  key: PlayStage;
  label: string;
  hint: string;
}[] = [
  { key: 'idea', label: 'Ideas', hint: 'Parked, no commitment' },
  { key: 'researching', label: 'Researching', hint: 'Digging in' },
  { key: 'building', label: 'Building', hint: 'Messaging + audience' },
  { key: 'ready', label: 'Ready', hint: 'Awaiting launch' },
  { key: 'live', label: 'Live', hint: 'In market' },
  { key: 'retired', label: 'Retired', hint: 'Archived' },
];

const STAGE_TONE: Record<PlayStage, string> = {
  idea: 'text-evari-dim bg-evari-surfaceSoft',
  researching: 'bg-evari-gold text-evari-goldInk',
  building: 'bg-evari-warn text-evari-goldInk',
  ready: 'bg-sky-400 text-evari-ink',
  live: 'bg-evari-success text-evari-ink',
  retired: 'text-evari-dimmer bg-evari-surfaceSoft',
};

export default async function PlaysPage() {
  const plays = await listPlays(createSupabaseAdmin());
  const byStage = new Map<PlayStage, Play[]>();
  for (const s of STAGES) byStage.set(s.key, []);
  for (const c of plays) {
    const arr = byStage.get(c.stage) ?? [];
    arr.push(c);
    byStage.set(c.stage, arr);
  }

  const total = plays.length;

  return (
    <>
      <TopBar
        title="Plays"
        subtitle={total + ' on the shelf — idea → live'}
      />

      <div className="p-6 max-w-[1400px] space-y-6">
        {/* Intro */}
        <div className="rounded-xl bg-evari-surface p-5 space-y-2">
          <div className="text-sm font-medium text-evari-text">
            Your play workbench
          </div>
          <p className="text-sm text-evari-dim leading-relaxed max-w-3xl">
            Each play is a living workbook — brief, research, target list,
            messaging, and a chat with Claude that carries the whole context.
            Spitball an idea, park it, come back to it, and graduate it through
            the stages when it's ready. Leads generated by a live play
            inherit its <code className="font-mono text-evari-text">sourceDetail</code>.
          </p>
          <div className="pt-2">
            <button
              type="button"
              className="inline-flex items-center gap-1.5 rounded-md bg-evari-gold text-evari-goldInk text-xs font-medium px-3 py-1.5 hover:bg-evari-gold/90"
            >
              <Plus className="h-3.5 w-3.5" />
              New play
            </button>
          </div>
        </div>

        {/* Stage columns */}
        {STAGES.map((s) => {
          const items = byStage.get(s.key) ?? [];
          if (items.length === 0) return null;
          return (
            <section key={s.key} className="space-y-2">
              <div className="flex items-center gap-3 px-1">
                <h2 className="text-sm font-medium text-evari-text capitalize">
                  {s.label}
                </h2>
                <span className="text-[11px] text-evari-dimmer">
                  {s.hint} · {items.length}
                </span>
              </div>
              <ul className="space-y-1">
                {items.map((c) => (
                  <li
                    key={c.id}
                    className="bg-evari-surface/60 rounded-md hover:bg-evari-surface transition-colors"
                  >
                    <Link
                      href={'/plays/' + c.id}
                      className="block p-4 rounded-md"
                    >
                      <div className="flex items-start justify-between gap-3 mb-1.5">
                        <div className="flex items-center gap-2 min-w-0">
                          {c.pinned && (
                            <Pin className="h-3 w-3 text-evari-gold shrink-0" />
                          )}
                          <div className="text-sm font-medium text-evari-text truncate">
                            {c.title}
                          </div>
                        </div>
                        <span
                          className={cn(
                            'shrink-0 text-[10px] uppercase tracking-wider font-semibold rounded-full px-2 py-0.5',
                            STAGE_TONE[c.stage],
                          )}
                        >
                          {c.stage}
                        </span>
                      </div>
                      <p className="text-xs text-evari-dim leading-relaxed line-clamp-2">
                        {c.brief}
                      </p>
                      <div className="flex items-center gap-3 mt-2 text-[10px] text-evari-dimmer tabular-nums">
                        <span>{c.research.length} notes</span>
                        <span>·</span>
                        <span>{c.targets.length} targets</span>
                        <span>·</span>
                        <span>{c.messaging.length} messages</span>
                        <span>·</span>
                        <span>{c.chat.length} chat turns</span>
                        <span className="ml-auto">
                          updated {relativeTime(c.updatedAt)}
                        </span>
                      </div>
                    </Link>
                  </li>
                ))}
              </ul>
            </section>
          );
        })}
      </div>
    </>
  );
}
