import { TopBar } from '@/components/sidebar/TopBar';
import { createSupabaseAdmin } from '@/lib/supabase/admin';
import { listPlays } from '@/lib/dashboard/repository';
import type { Play, PlayStage } from '@/lib/types';
import { NewStrategyButton } from '@/components/plays/NewStrategyButton';
import { PlayRow } from '@/components/plays/PlayRow';

const STAGES: {
  key: PlayStage;
  label: string;
  hint: string;
}[] = [
  { key: 'idea', label: 'Ideas', hint: 'Parked, no commitment' },
  { key: 'researching', label: 'Researching', hint: 'Digging in' },
  { key: 'building', label: 'Building', hint: 'Messaging + audience' },
  { key: 'ready', label: 'Ready', hint: 'Awaiting launch' },
  { key: 'live', label: 'Live', hint: 'In market' },
  { key: 'retired', label: 'Retired', hint: 'Archived' },
];

export default async function PlaysPage() {
  const plays = await listPlays(createSupabaseAdmin());
  const byStage = new Map<PlayStage, Play[]>();
  for (const s of STAGES) byStage.set(s.key, []);
  for (const c of plays) {
    const arr = byStage.get(c.stage) ?? [];
    arr.push(c);
    byStage.set(c.stage, arr);
  }

  const total = plays.length;

  return (
    <>
      <TopBar
        title="Strategy"
        subtitle={total + ' on the shelf — idea → live'}
      />

      <div className="p-6 space-y-6">
        {/* Intro */}
        <div className="rounded-xl bg-evari-surface p-5 space-y-2">
          <div className="text-sm font-medium text-evari-text">
            Your strategy workbench
          </div>
          <p className="text-sm text-evari-dim leading-relaxed max-w-3xl">
            Each strategy is a living workbook — brief, research, target list,
            messaging, and a chat with Claude that carries the whole context.
            Spitball an idea, park it, come back to it, and graduate it through
            the stages when it's ready. Leads generated by a live strategy
            inherit its <code className="font-mono text-evari-text">sourceDetail</code>.
          </p>
          <div className="pt-2">
            <NewStrategyButton />
          </div>
        </div>

        {/* Stage columns */}
        {STAGES.map((s) => {
          const items = byStage.get(s.key) ?? [];
          if (items.length === 0) return null;
          return (
            <section key={s.key} className="space-y-2">
              <div className="flex items-center gap-3 px-1">
                <h2 className="text-sm font-medium text-evari-text capitalize">
                  {s.label}
                </h2>
                <span className="text-[11px] text-evari-dimmer">
                  {s.hint} · {items.length}
                </span>
              </div>
              <ul className="space-y-1">
                {items.map((c) => (
                  <PlayRow key={c.id} play={c} />
                ))}
              </ul>
            </section>
          );
        })}
      </div>
    </>
  );
}
